@baseUri = http://127.0.0.1:3000/api 

### generate cover
POST {{baseUri}}/gen-cover
Content-Type: application/json

{
    "description": "a red car named Tesla"
}

### get covers
POST {{baseUri}}/get-covers
Content-Type: application/json

{
    
}

### delete user product
DELETE {{baseUri}}/delete-user-product
Content-Type: application/json
Cookie: __clerk_db_jwt=dvb_2rF7jNnyhvVYKFInQz5zszgHoyi;


{
    "userProductId": 17
}

# To get auth token:
# 1. Log into your app in browser
# 2. Open dev tools > Network tab
# 3. Find any request to your API
# 4. Copy the "Authorization" header value
# 5. Set it as a variable in your HTTP client environment
### test google image search
GET {{baseUri}}/get-product-image?brand=Shiseido&name=Synchro%20Skin%20Radiant%20Lifting%20Foundation
Content-Type: application/json
Cookie: __clerk_db_jwt=dvb_2rF7jNnyhvVYKFInQz5zszgHoyi;

### test another product search
GET {{baseUri}}/get-product-image?brand=La%20Mer&name=Cr%C3%A8me%20de%20la%20Mer
Content-Type: application/json
Cookie: __clerk_db_jwt=dvb_2rF7jNnyhvVYKFInQz5zszgHoyi;

### test SK-II product search
GET {{baseUri}}/get-product-image?brand=SK-II&name=Facial%20Treatment%20Essence
Content-Type: application/json
Cookie: __clerk_db_jwt=dvb_2rF7jNnyhvVYKFInQz5zszgHoyi;
